[project]
name = "pymusicbrowser"
version = "0.1.0"
description = "Python Music Browser - A music browser/player."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "peewee>=3.18.1",
    "tinytag>=2.1.1",
]
